[env]
_.path = [
  # adds a path relative to the mise.toml, not PWD
  "./node_modules/.bin",
]
_.python.venv = { path = ".venv", create = true }

[tools]
node = "24.13.0"
pnpm = "10.30.1"
poetry = "latest"
pre-commit = "latest"
python = "3.13"
