name: Dockerfile Generation Workflow

on:
  workflow_dispatch:
    inputs:
      base-image:
        description: 'Base image for the Dockerfile'
        required: true
      output-directory:
        description: 'Directory to save the generated Dockerfile'
        required: false
      packages:
        description: 'Additional packages to install'
        required: false

jobs:
  generate-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate Dockerfile
        run: poetry run generate-dockerfile --base-image ${{ inputs.base-image }} ${{ inputs.output-directory && format('--output-dir {0}', inputs.output-directory) }} ${{ inputs.packages && format('--packages {0}', inputs.packages) }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          title: 'Add generated Dockerfile'
          body: 'This PR adds a Dockerfile generated by the Dockerfile Generation Workflow.'
          branch: 'generated-dockerfile'
